apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels: 
    app: myapp
    tier: front-end
spec:
  template:
     metadata:
       name: nginx
       labels: 
        app: nginx
        tier: front-end
     spec:
      containers:
       - image: nginx:latest
         name: nginx
  replicas: 3